include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "lib/generated/**"
  
  plugins:
    - custom_lint

linter:
  rules:
    # Additional rules for professional code quality
    prefer_relative_imports: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    use_super_parameters: true
    
    # File organization
    directives_ordering: true
    
    # Performance
    avoid_multiple_declarations_per_line: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    
    # Security & Safety
    secure_pubspec_urls: true
    
    # Documentation
    public_member_api_docs: false # Will enable selectively
    
    # Style consistency
    prefer_single_quotes: true
    require_trailing_commas: true
    
    # Disable rules that conflict with our architecture
    prefer_const_constructors: false
    avoid_print: false # We use logger instead
